### ISSUE TITLE
Wrong dependency in migration

### ISSUE THREAD

**Issue by SteveGZr** [wfehr/djangocms-time-wizard#4]
There's following line in the dependencies in the first migration:
`        ('time_wizard', '0001_initial'),`

This is not working correctly when trying to migrate. The second migration of django-time-wizard is failing, because it is applied after the migrations of djangocms-time-wizard.

The correct order to migrate would be:

django-time-wizard 0001
django-time-wizard 0002
django-time-wizard 0003
djangocms-time-wizard 0001
and so on..

**Comment by SteveGZr** [comment]
See #5

**Comment by wfehr** [comment]
Thanks for reporting! Your PR is merged.

Fixed by 28b51ca.
